version: "0.0.1"
services:
  nginx:
    hostname: "nginx"
    image: bitnami/nginx:latest
  models:
    hostname: "models"
    ports:
      - "4000:4000"
    image: idlewater2/models:v0.0.1
    environment:
      DATABASE: caa
      DRIVER: mysql
      HOST: host.docker.internal
      PASSWORD: RxDragDb
      PORT: "3306"
      USER: root
  schedule:
    hostname: "schedule"
    ports:
      - "4002:4002"
    image: idlewater2/schedule:v0.0.1
    environment:
      DATABASE: caa
      DRIVER: mysql
      HOST: host.docker.internal
      PASSWORD: RxDragDb
      PORT: "3306"
      USER: root
  gateway:
    hostname: "gateway"
    ports:
      - "8081:8081"
    image: idlewater2/gateway:v0.0.1
    depends_on:
      - models
      - schedule
  simuserver:
    hostname: "simuserver"
    ports:
      - "8080:8080"
    image: idlewater2/simuserver:latest
